### Data structuring & Cleaning

In [15]:
import pandas as pd
import os
pwd = os.getcwd()
df = pd.read_csv(pwd + "//raw_datas_job_postings.csv")
df['ID'] = df.index + 1
df.set_index('ID')

,Date,Job_title,Job_type,Salary,Hours,Description,Link
ID,,,,,,,
1,"Apr 20, 2026","['Data Analyst', 'Analyst']",Any,"40,000PHP p/m",40,We are currently on the lookout for a Data Ana...,https://www.onlinejobs.ph/jobseekers/job/Full-...
2,"Apr 19, 2026","['Real Estate', 'Real Estate', 'Research']",Full Time,$500 - $1100,40,Please review this job post completely before ...,https://www.onlinejobs.ph/jobseekers/job/Real-...
3,"Apr 19, 2026","['Data Analyst', 'Analyst', 'BI']",Any,900,TBD,About the Role\nWe are an Australian-based pri...,https://www.onlinejobs.ph/jobseekers/job/Loan-...
4,"Apr 17, 2026","['Data Analyst', 'Senior', 'Analyst']",Full Time,"$1,000-$1,500",40,Company:\nProsper IT Consulting\n\nPosition:\n...,https://www.onlinejobs.ph/jobseekers/job/Senio...
5,"Apr 17, 2026","['Data Analyst', 'Analyst', 'Performance']",Part Time,"1,310.00 - 1,810.00 per month",35,We are a remote team supporting digital advert...,https://www.onlinejobs.ph/jobseekers/job/Ads-D...
...,...,...,...,...,...,...,...
196,"Sep 29, 2023","['Field Service', 'Data Analyst', 'Analyst']",Full Time,Competitive and commensurate with exp...,40,Exciting Data Analyst Opportunity at a Stealth...,https://www.onlinejobs.ph/jobseekers/job/Excit...
197,"Sep 14, 2023","['Data Analyst', 'Analyst']",Full Time,"$1000-$1,500",40,"About Trinity Road: For 25 years, Trinity Road...",https://www.onlinejobs.ph/jobseekers/job/Data-...
198,"Sep 9, 2023","['STR', 'Data Analyst', 'Analyst', 'Specialist...",Any,NaN,TBD,Want to join an awesome team who are passionat...,https://www.onlinejobs.ph/jobseekers/job/Data-...
199,"Aug 22, 2023","['Data Analyst', 'Analyst', 'Financial']",Full Time,1000 USD,40,About the Employer:\n\nAmpla is a financial pl...,https://www.onlinejobs.ph/jobseekers/job/Finan...
200,"Jul 24, 2023","['Data Analyst', 'Analyst']",Full Time,1000,TBD,"Reps, LLC is looking to hire a highly motivate...",https://www.onlinejobs.ph/jobseekers/job/Callt...

### KEYWORDS

In [ ]:
skills = [
    "SQL", "Python", "Excel", "Tableau", "Power BI"," BI",
    "Visual", "Statistic", "Machine Learning", " ML ", " AI", "Artificial Intelligence",
    "Cleaning", "Wrangling", "ETL", "Big Data", "Data Modeling",
    "Intelligence", "Reporting", "Dashboard", "A/B",
    "Predictive", "Data Mining", "Google Sheet","Google Analytics", "Looker",
    "Snowflake", "Spark", "Hadoop", "Critical Thinking", "Problem Solving",
    "Communication", "Stakeholder", "Management", "Governance", "KPI",
    "Metrics", "Pipeline", "Warehouse", "Azure", "AWS", "GCP",
    "Pandas", "NumPy", "Matplotlib", "Seaborn", "Jupyter", "Git",
    "Storytelling", "Regression", "Hypothesis",
    "Strategy", "spreadsheet"
]

responsibility = [
    "analyze", "report", "dashboards", "trends", "insights",
    "decision-making", "collaborate", "clean", "organize", "monitor",
    "present", "findings", "track", "KPI", "build", "interpret",
    "gather requirements", "automate", "accuracy", "datasets", "analysis",
    "visual", "solve", "business problems", "communicate", "metrics",
    "validation", "stakeholders", "extract", "transform", "load", "query",
    "document", "forecast", "trends"
]

qualifications = [
    "bachelor degree", "graduate", "education", "master's degree", "mathematics", "computer science", "certificate",
    "engineering", "economics", "information technology", "I.T", "data science", "experience",
    "excellent communication skills", "certifications", "Google Data Analytics",
    "Microsoft Certified", "AWS Certified",
    "portfolio", "project", "internship", "entry", "mid",
    "senior", "internet connection"
]

In [17]:
def comparison(description, keywords):
    """
    Checks which keywords from a list appear in the job description.

    Args:
        description (str): Full text of the job posting.
        keywords (list):   List of keywords to search for.

    Returns:
        list: Keywords found in the description (case-insensitive match).
    """
    found = []
    for word in keywords:
        if word.lower() in description.lower():
            found.append(word)
    return found
df["Skills"] = df['Description'].apply(lambda x: comparison(x, skills))
df["Responsibilities"] = df['Description'].apply(lambda x: comparison(x, responsibility))
df["Qualifications"] = df['Description'].apply(lambda x: comparison(x, qualifications))
copy_df = df.copy()
copy_df.drop(columns=["Description"], inplace=True)
copy_df.to_csv("Parsed_dataset.csv", index=False) #Exporting the output for Streamlit

The salary has no strict format, it must be cleaned and interpreted in how much it would be in the format of hourly salary

I used AI to clean the dataset with manual review and correction

In [18]:
### Putting the values of the cleaned column salary to the main dataset salary column
import numpy as np

values = """
5.00
5.62
7.81
9.75
4.66
4.69

4.66
5.00
4.69
7.88
5.00

5.00
3.13
6.03
4.69
10.00

4.69

7.50

5.00

5.00
4.66
7.68
7.68
8.00
10.96
13.75
6.00
7.00
3.12
5.00
9.45

15.62
17.19
17.19
8.59
14.00
4.00
15.00
4.48
5.00


6.50
6.25
7.29
4.69


3.80
5.00
4.11
7.50
4.69
10.94
6.25
7.50
4.69
3.12
6.50
1.88
8.00
7.50
4.69
4.06
8.00
13.16
6.25
7.81
137.50
7.50
6.03
7.81

6.25
3.12
6.25
5.62
2.19
5.00
2.50

7.50
5.00
2.50
3.00
3.00

10.00
5.00
10.00
2.63
4.39

10.00
4.69
6.25

4.66
5.00
4.00
4.39
6.25
10.50
9.38
10.94
6.25
21.93
6.50
5.00
6.09
6.88


3.12
11.24
8.22
8.22
5.00
4.69
5.62

7.68
7.50
6.56
5.00
10.00
15.62
6.25
8.50
5.00

7.50
4.39
35.00
3.75
3.12
3.12

6.25
10.41

10.41
1.88
14.00
4.00
10.00

125.00
5.00
9.00
7.00

10.00

4.11
3.75
6.88
4.38
3.12
18.75
10.00
6.25
6.25
8.38
6.25
5.00

6.25
6.25
6.25

6.25
6.25

6.56
7.12
6.00
6.58
4.78
5.00
5.00
5.00
4.38
3.12
187.50
3.12

7.81

6.25
6.25
10.96"""

# Parse values — blank lines become NaN, dollar signs stripped
new_salary = [
    np.nan if line.strip() == "" else float(line.strip().replace("$", ""))
    for line in values.split("\n")
]
# Pad with NaN at the end to match
if len(new_salary) < len(copy_df):
    new_salary += [np.nan] * (len(copy_df) - len(new_salary))
# Assign to column (must match row count)
copy_df["Salary"] = new_salary
copy_df

,Date,Job_title,Job_type,Salary,Hours,Link,ID,Skills,Responsibilities,Qualifications
0,"Apr 20, 2026","['Data Analyst', 'Analyst']",Any,NaN,40,https://www.onlinejobs.ph/jobseekers/job/Full-...,1,"[Google Sheet, Metrics]","[report, build, metrics]",[experience]
1,"Apr 19, 2026","['Real Estate', 'Real Estate', 'Research']",Full Time,5.00,40,https://www.onlinejobs.ph/jobseekers/job/Real-...,2,"[Excel, Cleaning, Reporting, Google Sheet, Man...","[report, clean, organize, accuracy, datasets, ...","[familiarity, experience, detail-oriented]"
2,"Apr 19, 2026","['Data Analyst', 'Analyst', 'BI']",Any,5.62,TBD,https://www.onlinejobs.ph/jobseekers/job/Loan-...,3,"[Excel, BI, Communication, Management]",[clean],"[experience, detail-oriented]"
3,"Apr 17, 2026","['Data Analyst', 'Senior', 'Analyst']",Full Time,7.81,40,https://www.onlinejobs.ph/jobseekers/job/Senio...,4,"[SQL, Python, Communication, Git]",[analysis],"[proficiency, experience, portfolio, senior]"
4,"Apr 17, 2026","['Data Analyst', 'Analyst', 'Performance']",Part Time,9.75,35,https://www.onlinejobs.ph/jobseekers/job/Ads-D...,5,"[Excel, Reporting, Dashboard, Google Sheet, Co...","[report, dashboards, trends, insights, monitor...",[experience]
...,...,...,...,...,...,...,...,...,...,...
195,"Sep 29, 2023","['Field Service', 'Data Analyst', 'Analyst']",Full Time,7.81,40,https://www.onlinejobs.ph/jobseekers/job/Excit...,196,"[Excel, Cleaning, Communication, Management, KPI]","[analyze, report, trends, insights, decision-m...","[proficiency, familiarity, experience, project]"
196,"Sep 14, 2023","['Data Analyst', 'Analyst']",Full Time,NaN,40,https://www.onlinejobs.ph/jobseekers/job/Data-...,197,"[SQL, Python, Excel, Tableau, Power BI, BI, V...","[report, dashboards, KPI, analysis, visual, qu...","[mathematics, computer science, data science, ..."
197,"Sep 9, 2023","['STR', 'Data Analyst', 'Analyst', 'Specialist...",Any,6.25,TBD,https://www.onlinejobs.ph/jobseekers/job/Data-...,198,"[ BI, Statistic, Reporting, Google Analytics, ...","[analyze, report, trends, insights, collaborat...","[experience, portfolio]"
198,"Aug 22, 2023","['Data Analyst', 'Analyst', 'Financial']",Full Time,6.25,40,https://www.onlinejobs.ph/jobseekers/job/Finan...,199,"[Excel, BI, Git, spreadsheet]","[report, build, accuracy, communicate, load]","[experience, team player]"
199,"Jul 24, 2023","['Data Analyst', 'Analyst']",Full Time,10.96,TBD,https://www.onlinejobs.ph/jobseekers/job/Callt...,200,"[Management, Strategy]","[analyze, report, interpret, analysis, load]","[proven experience, experience]"

The values inside the columns of Job_title, Skills, Responsibilities, Qualifications are going to be split and have their own table along with their IDs and Salary then have their values exploded since it has multiple values containing in every cell

In doing so, it will be easier to present and perform analysis to the dataset with respect to the particular items of each columns

In [19]:
jobTitleTable = copy_df[["ID", "Job_title", "Salary"]].copy()
skillsTable = copy_df[['ID', 'Skills', 'Salary']].copy()
responsibilitiesTable = copy_df[['ID', 'Responsibilities', 'Salary']].copy()
QualificationsTable = copy_df[['ID', 'Qualifications', 'Salary']].copy()
single_Val_Col_Table = copy_df[['ID', 'Date', 'Job_type', 'Hours', 'Salary', 'Link']].copy()
print(jobTitleTable)
print(skillsTable)
print(responsibilitiesTable)
print(QualificationsTable)

      ID                                          Job_title  Salary
0      1                        ['Data Analyst', 'Analyst']     NaN
1      2         ['Real Estate', 'Real Estate', 'Research']    5.00
2      3                  ['Data Analyst', 'Analyst', 'BI']    5.62
3      4              ['Data Analyst', 'Senior', 'Analyst']    7.81
4      5         ['Data Analyst', 'Analyst', 'Performance']    9.75
..   ...                                                ...     ...
195  196       ['Field Service', 'Data Analyst', 'Analyst']    7.81
196  197                        ['Data Analyst', 'Analyst']     NaN
197  198  ['STR', 'Data Analyst', 'Analyst', 'Specialist...    6.25
198  199           ['Data Analyst', 'Analyst', 'Financial']    6.25
199  200                        ['Data Analyst', 'Analyst']   10.96

[200 rows x 3 columns]
      ID                                             Skills  Salary
0      1                            [Google Sheet, Metrics]     NaN
1      2  [Excel, Cleaning, Reporting, Google Sheet, Man...    5.00
2      3            [Excel,  BI, Communication, Management]    5.62
3      4                  [SQL, Python, Communication, Git]    7.81
4      5  [Excel, Reporting, Dashboard, Google Sheet, Co...    9.75
..   ...                                                ...     ...
195  196  [Excel, Cleaning, Communication, Management, KPI]    7.81
196  197  [SQL, Python, Excel, Tableau, Power BI,  BI, V...     NaN
197  198  [ BI, Statistic, Reporting, Google Analytics, ...    6.25
198  199                     [Excel,  BI, Git, spreadsheet]    6.25
199  200                             [Management, Strategy]   10.96

[200 rows x 3 columns]
      ID                                   Responsibilities  Salary
0      1                           [report, build, metrics]     NaN
1      2  [report, clean, organize, accuracy, datasets, ...    5.00
2      3                                            [clean]    5.62
3      4                                         [analysis]    7.81
4      5  [report, dashboards, trends, insights, monitor...    9.75
..   ...                                                ...     ...
195  196  [analyze, report, trends, insights, decision-m...    7.81
196  197  [report, dashboards, KPI, analysis, visual, qu...     NaN
197  198  [analyze, report, trends, insights, collaborat...    6.25
198  199       [report, build, accuracy, communicate, load]    6.25
199  200       [analyze, report, interpret, analysis, load]   10.96

[200 rows x 3 columns]
      ID                                     Qualifications  Salary
0      1                                       [experience]     NaN
1      2         [familiarity, experience, detail-oriented]    5.00
2      3                      [experience, detail-oriented]    5.62
3      4       [proficiency, experience, portfolio, senior]    7.81
4      5                                       [experience]    9.75
..   ...                                                ...     ...
195  196    [proficiency, familiarity, experience, project]    7.81
196  197  [mathematics, computer science, data science, ...     NaN
197  198                            [experience, portfolio]    6.25
198  199                          [experience, team player]    6.25
199  200                    [proven experience, experience]   10.96

[200 rows x 3 columns]

In [20]:
modified_df = copy_df.copy()
# Removing the [] and ' then split strings by comma into a list in The Job_title Column
jobTitleTable[jobTitleTable.columns[1]] = jobTitleTable[jobTitleTable.columns[1]].str.replace("]", "", regex=False).str.replace("[", "", regex=False).str.replace("'", "", regex=False).str.split(", ")

In [21]:
### All the tables are now cleaned to be explode
jobTitleTable = jobTitleTable.explode(jobTitleTable.columns[1])
skillsTable = skillsTable.explode(skillsTable.columns[1])
responsibilitiesTable = responsibilitiesTable.explode(responsibilitiesTable.columns[1])
QualificationsTable = QualificationsTable.explode(QualificationsTable.columns[1])
skillsTable.to_csv("Skills_table.csv", index=False)
QualificationsTable.to_csv("Qualifications_table.csv", index=False)
responsibilitiesTable.to_csv("Responsibilities_table.csv", index=False)
skillsTable

      ID        Skills  Salary
0      1  Google Sheet     NaN
0      1       Metrics     NaN
1      2         Excel    5.00
1      2      Cleaning    5.00
1      2     Reporting    5.00
..   ...           ...     ...
198  199            BI    6.25
198  199           Git    6.25
198  199   spreadsheet    6.25
199  200    Management   10.96
199  200      Strategy   10.96

[1473 rows x 3 columns]

# EDA
## Questions to Ask
### What are the most frequently required Skills and Qualifications?

#### - Skills

In [22]:
value_counts_skills = skillsTable.Skills.value_counts()
value_counts_skills

Skills
Excel                134
Communication        100
Reporting             95
Dashboard             93
Visual                80
 BI                   79
Management            71
Metrics               70
SQL                   67
Google Sheet          64
 AI                   43
Power BI              43
Strategy              41
Tableau               40
KPI                   39
Python                39
Git                   35
Stakeholder           32
spreadsheet           32
Statistic             29
Looker                26
Google Analytics      26
Pipeline              26
Data Modeling         19
Cleaning              18
Intelligence          16
A/B                   15
ETL                   14
Predictive            11
Warehouse             10
Pandas                 9
Critical Thinking      6
Storytelling           6
Governance             6
Snowflake              6
Machine Learning       6
NumPy                  4
AWS                    3
Azure                  3
Big Data               2
Problem Solving        2
Regression             1
GCP                    1
Matplotlib             1
Jupyter                1
Data Mining            1
Spark                  1
Name: count, dtype: int64

In [23]:

value_counts_skills.sort_values(ascending=False)
value_counts_skills

Skills
Excel                134
Communication        100
Reporting             95
Dashboard             93
Visual                80
 BI                   79
Management            71
Metrics               70
SQL                   67
Google Sheet          64
 AI                   43
Power BI              43
Strategy              41
Tableau               40
KPI                   39
Python                39
Git                   35
Stakeholder           32
spreadsheet           32
Statistic             29
Looker                26
Google Analytics      26
Pipeline              26
Data Modeling         19
Cleaning              18
Intelligence          16
A/B                   15
ETL                   14
Predictive            11
Warehouse             10
Pandas                 9
Critical Thinking      6
Storytelling           6
Governance             6
Snowflake              6
Machine Learning       6
NumPy                  4
AWS                    3
Azure                  3
Big Data               2
Problem Solving        2
Regression             1
GCP                    1
Matplotlib             1
Jupyter                1
Data Mining            1
Spark                  1
Name: count, dtype: int64

#### - Qualifications

In [24]:
value_counts_qualifications = QualificationsTable["Qualifications"].value_counts().sort_values(ascending=False)
value_counts_qualifications

Qualifications
experience                        176
proficiency                        73
data-driven                        68
project                            64
familiarity                        63
detail-oriented                    50
proven experience                  35
portfolio                          33
entry                              25
education                          23
senior                             21
engineering                        20
hands-on experience                18
data science                       16
internet connection                13
excellent communication skills     12
mathematics                        10
strong analytical skills           10
computer science                    9
problem solver                      8
mid                                 8
results-driven                      7
economics                           6
certifications                      5
fast learner                        5
demonstrated experience             4
graduate                            4
team player                         4
information technology              3
self-motivated                      2
master's degree                     2
Google Data Analytics               1
Microsoft Certified                 1
certificate                         1
internship                          1
Name: count, dtype: int64

### What are the most frequent Responsibilities?

In [25]:
value_counts_responsibilities = responsibilitiesTable["Responsibilities"].value_counts().sort_values(ascending=False)
value_counts_responsibilities

Responsibilities
trends                 160
report                 142
analysis               119
insights               110
build                   96
analyze                 87
dashboards              87
track                   83
visual                  80
metrics                 70
accuracy                61
collaborate             60
clean                   57
monitor                 50
interpret               47
document                47
present                 47
datasets                40
KPI                     39
extract                 38
transform               36
query                   36
decision-making         36
communicate             35
stakeholders            32
organize                31
automate                31
findings                26
load                    23
validation              22
solve                   21
forecast                17
gather requirements      1
Name: count, dtype: int64

## Average Salary for each Skills, Qualifications, and Responsibilities for a Data Analyst

# Skills

In [26]:
skills_ave = skillsTable.groupby('Skills')['Salary'].agg(Average='mean', Count='count').sort_values(by='Count',ascending=False).reset_index()
skills_ave
### It is sorted by Count to ensure reliability of its mean/average salary

               Skills     Average  Count
0               Excel    8.921667    114
1       Communication    8.276463     82
2           Reporting    8.769875     80
3           Dashboard   10.475714     77
4                  BI    9.242576     66
5              Visual   11.662121     66
6          Management   11.669000     60
7             Metrics   12.507544     57
8                 SQL    7.396111     54
9        Google Sheet    9.683400     50
10           Strategy   15.147297     37
11                KPI    6.948889     36
12                 AI    7.035833     36
13           Power BI    7.610556     36
14                Git   12.030000     31
15            Tableau   12.004194     31
16             Python    6.454194     31
17        spreadsheet    7.114444     27
18        Stakeholder   12.775000     24
19   Google Analytics   13.713750     24
20           Pipeline   12.834545     22
21          Statistic   15.929545     22
22             Looker   19.740476     21
23      Data Modeling    7.234118     17
24           Cleaning    6.538000     15
25                A/B    8.505714     14
26                ETL    7.110000     13
27       Intelligence    6.934167     12
28         Predictive    6.125455     11
29          Warehouse    7.422500      8
30             Pandas    7.332857      7
31         Governance    5.205000      6
32  Critical Thinking   10.456667      6
33       Storytelling    6.276667      6
34   Machine Learning    5.022500      4
35              NumPy    7.890000      4
36                AWS    5.000000      3
37          Snowflake    7.613333      3
38              Azure    8.020000      3
39           Big Data    5.780000      2
40        Data Mining    5.000000      1
41                GCP    2.500000      1
42            Jupyter   10.000000      1
43         Matplotlib   10.000000      1
44              Spark    5.000000      1
45    Problem Solving  137.500000      1
46         Regression    4.690000      1

# Qualifications

In [27]:
qualifications_ave = QualificationsTable.groupby('Qualifications')['Salary'].agg(Average='mean', Count='count').sort_values(by='Count',ascending=False).reset_index()
qualifications_ave

                    Qualifications    Average  Count
0                       experience   9.626622    148
1                      data-driven  11.306610     59
2                      proficiency  11.876780     59
3                      familiarity   6.628113     53
4                          project  12.584423     52
5                  detail-oriented   6.522273     44
6                        portfolio  11.982581     31
7                proven experience  17.284000     30
8                            entry  11.459545     22
9                           senior  19.582500     20
10                       education  24.432000     20
11                     engineering  16.795625     16
12             hands-on experience  15.490000     15
13             internet connection   8.660000     11
14                    data science   6.496364     11
15  excellent communication skills   5.778000     10
16                     mathematics  30.843750      8
17        strong analytical skills   6.665714      7
18                  problem solver  24.511429      7
19                computer science   7.527143      7
20                             mid   6.344286      7
21                  results-driven  25.208333      6
22         demonstrated experience   6.750000      4
23                        graduate   7.120000      4
24                     team player   7.422500      4
25                    fast learner  39.545000      4
26                  certifications   7.810000      3
27          information technology   6.565000      2
28                       economics  12.500000      2
29           Google Data Analytics  13.750000      1
30                     certificate   7.500000      1
31                      internship   8.220000      1
32                 master's degree   7.680000      1
33                  self-motivated   4.780000      1
34             Microsoft Certified        NaN      0

# Responsibilities

In [28]:
responsibility_ave = responsibilitiesTable.groupby('Responsibilities')['Salary'].agg(Average='mean', Count='count').sort_values(by='Count',ascending=False).reset_index()
responsibility_ave

       Responsibilities    Average  Count
0                trends  10.798406    138
1                report   9.192521    119
2              analysis  11.123838     99
3              insights  11.798085     94
4                 build   6.872289     83
5                 track  10.410135     74
6            dashboards  10.500411     73
7               analyze   9.452361     72
8                visual  11.662121     66
9               metrics  12.507544     57
10          collaborate  12.766604     53
11             accuracy   9.497059     51
12                clean   6.751020     49
13              monitor  12.382766     47
14             document   7.019286     42
15            interpret  14.030000     40
16              present   6.779744     39
17                  KPI   6.948889     36
18            transform   6.670303     33
19              extract   7.278750     32
20             datasets   6.901935     31
21                query  11.288621     29
22      decision-making  16.927500     28
23             automate   6.190741     27
24             organize   6.621852     27
25          communicate  17.078400     25
26         stakeholders  12.775000     24
27             findings   8.273810     21
28                 load  12.553333     21
29           validation  12.798421     19
30             forecast   6.042500     16
31                solve  14.835000     16
32  gather requirements        NaN      0